FROM python:3.10-slim

WORKDIR /home/blog-simples

RUN apt-get update -y && apt-get install -y build-essential libpq-dev

COPY . .
RUN pip install -r requirements.txt -U

EXPOSE 8000

CMD gunicorn wsgi:app