"""empty message

Revision ID: 0f073d261370
Revises: 37eb4de20a34
Create Date: 2022-11-30 17:51:23.276502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f073d261370'
down_revision = '37eb4de20a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_timestamp'), 'reply', ['timestamp'], unique=False)
    op.drop_index('ix_message_timestamp', table_name='message')
    op.drop_table('message')
    op.add_column('post', sa.Column('title', sa.Text(), nullable=True))
    op.alter_column('post', 'body',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('user', 'about_me',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'about_me',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('post', 'body',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('post', 'title')
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('body', mysql.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name='message_ibfk_1'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='message_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_message_timestamp', 'message', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_reply_timestamp'), table_name='reply')
    op.drop_table('reply')
    # ### end Alembic commands ###
