"""empty message

Revision ID: 996d7305af96
Revises: a12bcf47fed7
Create Date: 2022-10-04 18:38:39.018660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996d7305af96'
down_revision = 'a12bcf47fed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'body',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
    # ### end Alembic commands ###
